### ISSUE TITLE
Petstore example broken

### ISSUE THREAD

**Issue by kvlahromei** [pipermerriam/flex#76]
The [petstore example](http://petstore.swagger.io) is pretty popular for newbies at swagger.io because it's simple and often used. Unfortunatly flex 4.01 seems to have problems with the current [specs. file](http://petstore.swagger.io/v2/swagger.json):

```
ValidationError: 'info':
    - 'contact':
        - 'type':
            - u"Got value `{u'email': u'apiteam@wordnik.com'}` of type `object`.
  Value must be of type(s): `(u'string',)`"
    - 'license':
        - 'type':
            - u"Got value `{u'url': u'http://www.apache.org/licenses/LICENSE-2.0
.html', u'name': u'Apache 2.0'}` of type `object`.  Value must be of type(s): `(
u'string',)`"
'paths':
    - u'/pet/findByStatus':
        - 'get':
            - 'parameters':
                - 'default':
                    - u"The value of `default` must be of one of the declared ty
pes for the schema.  `available` is not one of `[u'array']`"
    - u'/pet/{petId}/uploadImage':
        - 'post':
            - 'parameters':
                - 'type':
                    - 'type':
                        - 'enum':
                            - u"Invalid value.  file is not one of the available
 options ([u'null', u'boolean', u'integer', u'number', u'string', u'array'])"
```

Can anybody please tell if this is already in focus (and maybe covered by other issues) ?

**Comment by pipermerriam** [comment]
Not covered by other issues and actually looks like a couple of separate bugs.  Thanks for reporting.

**Comment by pipermerriam** [comment]
Alright, this is the one section I'm having trouble with.

```
'paths':
    - u'/pet/findByStatus':
        - 'get':
            - 'parameters':
                - 'default':
                    - u"The value of `default` must be of one of the declared ty
pes for the schema.  `available` is not one of `[u'array']`"
```

And from the petstore schema.

```javascript
    "\/pet\/findByStatus": {
      "get": {
        "tags": [
          "pet"
        ],
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma seperated strings",
        "operationId": "findPetsByStatus",
        "consumes": [
          "application\/xml",
          "application\/json"
        ],
        "produces": [
          "application\/xml",
          "application\/json"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "default": "available",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        ],
```

According to swagger, the value for `default` is validated the same way as specified in the json schema spec.

> Sets a default value to the parameter. The type of the value depends on the defined type. See http://json-schema.org/latest/json-schema-validation.html#anchor101.

And then if you follow that link to see what json schema has to say.

> There are no restrictions placed on the value of this keyword. 

So, is the right thing to do here to just remove all validation of this keyword?  I *think* at the time I wrote this validation, I was working under the assumption that the value of `default` should be validated to be of the correct type.  Now I can't find anything in the schema suggesting this validation should occur.

Just want to be sure that I'm not missing something before I remove that validation.

**Comment by pipermerriam** [comment]
cc @kvlahromei  on my previous comment.

**Comment by webron** [comment]
This one's a bit tricky and is an edge-case.

Generally speaking (and Swagger spec does say that) that the type of the `default` value must be the one associated with the type of the parameter. This is *not* the same as the definition in JSON Schema and it supersedes it.

The problem here is that the type of of the parameter is `array` and as such you'd expect the default value to be `[ "available" ]`. However, the real problem is that the `collectionFormat` is `multi` - that means the value is *not* an array but is repeated as a single value. This is a use case I hadn't thought of and definitely needs to be clarified (I have an idea but need to process it first).

I'm not familiar with this specific project and how it does the validation, but please keep in mind that the JSON Schema we provide for validation can only cover part of the restrictions provided by the spec itself. For example, it does not add said restriction of type on the `default` value.

**Comment by pipermerriam** [comment]
> Generally speaking (and Swagger spec does say that) that the type of the default value must be the one associated with the type of the parameter.

I remember this, but could not find it in the spec when I went to look yesterday.  The only thing I could find was language saying that it conformed to JSON Schema.

> I'm not familiar with this specific project and how it does the validation

All of the validation is entirely custom, so I'm able to conform to anything that Swagger specifies.

**Comment by pipermerriam** [comment]
@webron 

> The problem here is that the type of of the parameter is array and as such you'd expect the default value to be `[ "available" ]`. However, the real problem is that the `collectionFormat` is `multi` - that means the value is not an array but is repeated as a single value. This is a use case I hadn't thought of and definitely needs to be clarified (I have an idea but need to process it first).

I don't quite follow you here.  My understanding is that for `collectionFormat=multi` that `/?foo=bar&foo=baz' that the parsed value would be `["foo", "bar"]`.  Similarly, that `/?foo=bar` would be parsed as `["bar"]` assuming that the type is specified to be `array`.  I'm having trouble understanding what you mean when you say *that means the value is not an array but is repeated as a single value.*

**Comment by webron** [comment]
This is where it is defined - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#itemsDefault.

That's exactly what it means. `/?foo=bar&foo=baz` - `foo` is repeated but each time has a single value. That's not an array in its classic form.

**Comment by pipermerriam** [comment]
When I read *Sets a default value to the data type. The type of the value depends on the defined type*.  I don't interpret it to mean that the value is required to conform to the `type`.  My reasoning is that the statement doesn't use any of the language from RFC2119.  Would you be ok with me submitting a PR to change those statements to say:

> Sets the default value of the data type.  See http://json-schema.org/latest/json-schema-validation.html#anchor101.  Unlike JSON Schema this value MUST conform to the defined type for this parameter/property/header/.

Also, you stated

> That's exactly what it means. `/?foo=bar&foo=baz` - foo is repeated but each time has a single value. That's not an array in its classic form.

Could you clarify.  What should the following two values be parsed as given `type: "array", collectionFormat: "multi", items: {type: "string"}`

* `/?foo=bar&foo=baz`
* `/?foo=bar`

**Comment by webron** [comment]
I'd accept it if it'll be modified for *all* `default` value descriptions, each linking the word `type` to its own type and being explicit to container it's held in (that is, not "this parameter/property/header" but explicitly the container itself).

I don't follow your second question.

**Comment by pipermerriam** [comment]
> I don't follow your second question.

My interpretation of the correct way to parse the following query strings under the schema `type: "array", collectionFormat: "multi", items: {type: "string"}` is:

* `/?foo=bar&foo=baz` > `["bar", "baz"]`
* `/?foo=bar` > `["bar"]`

If this is correct, it seems to me that the value of `default` for MUST be an array of strings, and not a standalone string (as is present in the referenced petstore example) since a there is no situation in which you would get just the string `"bar"` from a querystring.

Now, the pragmatic part of me:

It is not unreasonable to parse `/?foo=bar` to mean either `foo = "bar"` or `foo = ["bar"]`, often defaulting to the first.  This approach seems to be somewhat common.  Given this, would it be correct to say that Swagger accepts parsing `/?foo=bar` as a singular string (`foo = "bar"`) as an acceptable *special* case.  If so, would you be ok with me submitting a PR stating as much in the `ParameterObject` part of the spec.

**Comment by pipermerriam** [comment]
https://github.com/swagger-api/swagger-spec/pull/338

**Comment by pipermerriam** [comment]
@webron , wondering if you've had time to look at the clarification I posted

**Comment by webron** [comment]
@pipermerriam - sorry, was on a holiday and weekend and life.

In any case, I've merged the PR.

As for the value of the default for array, I tend to agree with you in general, though disagree with the either/or use case because we have to keep it simple. I would really appreciate it if you can open an issue on it on the swagger-spec repo and we can continue the discussion there.

**Comment by pipermerriam** [comment]
@webron sure thing.  Thanks for the feedback.

**Comment by pipermerriam** [comment]
Alright.  I've gotten a response on the issue https://github.com/swagger-api/swagger-spec/issues/343#issuecomment-128792251 from ron and it appears that the current validation is correct, and the linked petstore example is incorrect.  If the `type="array"` then the value of `default` must conform to the declared type.

**Comment by kvlahromei** [comment]
Thank you both for your investigations :-)
