### ISSUE TITLE
Support for model composition

### ISSUE THREAD

**Issue by ludug3r0** [pipermerriam/flex#81]
What about the feature of using discriminator and extends?

https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/models/modelWithComposition.json

**Comment by pipermerriam** [comment]
I'm supportive of it, but I don't know how soon I'd be able to get to it.

**Comment by adrpp** [comment]
I'd like to add support for 'allOf' (composition) into flex, but don't know where to start :)
Added a file "all_of" into flex.loading.common; could you push me into the right direction regarding where else this needs to be integrated ?

**Comment by pipermerriam** [comment]
You're off to the right start.

Step 1 is to actually validate the structure of the `allOf` keyword.  This looks like it needs to be an array of `schema` objects or references.

Step 2 is going to be a bit more complex.  You'll need to hook into `flex.validation.schema`.  I believe you may be able to add a new item to the `validator_mapping` dictionary in that module that loops over the schema objects in the `allOf` key and uses the `construct_schema_validators` function to create the appropriate validators.

Don't hesitate to ask if you have more questions.

**Comment by amygdalama** [comment]
I'd like this feature too! Are you still interested in implementing this @adrpp ? If not, I'd be happy to.

**Comment by adrpp** [comment]
@amygdalama feel free, I didn't come back to this yet and I'm struggling with some complex Types which would be easy to create with jsonscheme itself, but doesn't work / aren't supported by swagger (oneOf, anyOf -> https://github.com/OAI/OpenAPI-Specification/issues/57 & https://github.com/swagger-api/swagger-ui/issues/1056)

Still not sure if use flex or validator provided by "swagger-py-codegen" which looks a bit weak in some cases, or to write it from scratch. I'm missing Draft4Validator in this package and won't define (dicts) which were defined before in the yaml file ... 

just FYI, using allOf in order to be able to  'mix' models (for responses) won't work as soon as one of attributes is required.

**Comment by adrpp** [comment]
@amygdalama do u have any news / updates about this ? :)

**Comment by amygdalama** [comment]
Nope! Poked around a bit on Friday but didn't have enough time to do
anything substantial.

**Comment by armisael** [comment]
I stumbled upon this issue and worked a bit on it, please have a look at my pull request and contribute if anything is missing: #103

**Comment by pipermerriam** [comment]
closed via #103
